-- Remove votes referencing deleted clubs first (foreign key constraint)
DELETE FROM votes WHERE winner_id IN (SELECT id FROM clubs WHERE name IN ('A Seat at the Table','Associate Real Estate Council','BR Tech Strategy','Beta Alpha Psi','Business Club for Emerging Economies at Cornell','Business Review Club at Cornell','Canadian Business Club','Capitalista Collective Club','Christian Business Society','Computational & Quantitative Social Science at Cornell','Cornell Amateur Radio Club','Cornell Artificial Intelligence Investments club','Cornell Bitcoin Club','Cornell Chapter of International City/County Management Association','Cornell Credit Literacy Student Association','Cornell Current Club','Cornell Equity Derivatives Club','Cornell Growth Capital Club','Cornell ICPC Club','Cornell International Finance Club','Cornell Strategy Solutions Club','Cornell Technical Analysis Club','Cornell Venture and Entrepreneurship Club','Corporate Leadership Club','Delta Kappa Alpha Professional Cinematic Society','Diversity on the Street','Dyson Diversity Council at Cornell','EMBA Women','ETA Club at Cornell','Executive MBA Entrepreneurship Club at Cornell','Family Business Club','Federal Reserve Challenge Club','First Generation Investors at Cornell','Graduate Student Association for Economics','Healthcare Artificial Intelligence Collaborative Club','High Tech Club','Hospitality Business Club','Hotel Graduate Student Organization','Hotel Society, Collegiate Chapter','Human Capital Association','Investment Management Club','Johnson Consulting Club','Johnson Healthcare Club','Johnson MPS Student Council','Johnson Southeast Asian Club','LAW - Business Law Society','Media Guild, Inc','Mu Epsilon Delta','Nolan Research Student Association','Old Ezra Finance Club','Organization of Urban and Regional Studies','Professional Fraternity Council','Retail & Luxury Club','Scholars of Finance - Cornell Chapter','SensTech','Social Enterprise Group at Cornell','The Insurance Club at Cornell','The MergerSight Group at Cornell','The TRIBECA Club at Cornell','Undergraduate Human Capital Association','VC@Johnson','Ventures Accelerated','Women'));
DELETE FROM votes WHERE loser_id IN (SELECT id FROM clubs WHERE name IN ('A Seat at the Table','Associate Real Estate Council','BR Tech Strategy','Beta Alpha Psi','Business Club for Emerging Economies at Cornell','Business Review Club at Cornell','Canadian Business Club','Capitalista Collective Club','Christian Business Society','Computational & Quantitative Social Science at Cornell','Cornell Amateur Radio Club','Cornell Artificial Intelligence Investments club','Cornell Bitcoin Club','Cornell Chapter of International City/County Management Association','Cornell Credit Literacy Student Association','Cornell Current Club','Cornell Equity Derivatives Club','Cornell Growth Capital Club','Cornell ICPC Club','Cornell International Finance Club','Cornell Strategy Solutions Club','Cornell Technical Analysis Club','Cornell Venture and Entrepreneurship Club','Corporate Leadership Club','Delta Kappa Alpha Professional Cinematic Society','Diversity on the Street','Dyson Diversity Council at Cornell','EMBA Women','ETA Club at Cornell','Executive MBA Entrepreneurship Club at Cornell','Family Business Club','Federal Reserve Challenge Club','First Generation Investors at Cornell','Graduate Student Association for Economics','Healthcare Artificial Intelligence Collaborative Club','High Tech Club','Hospitality Business Club','Hotel Graduate Student Organization','Hotel Society, Collegiate Chapter','Human Capital Association','Investment Management Club','Johnson Consulting Club','Johnson Healthcare Club','Johnson MPS Student Council','Johnson Southeast Asian Club','LAW - Business Law Society','Media Guild, Inc','Mu Epsilon Delta','Nolan Research Student Association','Old Ezra Finance Club','Organization of Urban and Regional Studies','Professional Fraternity Council','Retail & Luxury Club','Scholars of Finance - Cornell Chapter','SensTech','Social Enterprise Group at Cornell','The Insurance Club at Cornell','The MergerSight Group at Cornell','The TRIBECA Club at Cornell','Undergraduate Human Capital Association','VC@Johnson','Ventures Accelerated','Women'));

-- Remove deleted clubs (preserves all other data)
DELETE FROM clubs WHERE name = 'A Seat at the Table';
DELETE FROM clubs WHERE name = 'Associate Real Estate Council';
DELETE FROM clubs WHERE name = 'BR Tech Strategy';
DELETE FROM clubs WHERE name = 'Beta Alpha Psi';
DELETE FROM clubs WHERE name = 'Business Club for Emerging Economies at Cornell';
DELETE FROM clubs WHERE name = 'Business Review Club at Cornell';
DELETE FROM clubs WHERE name = 'Canadian Business Club';
DELETE FROM clubs WHERE name = 'Capitalista Collective Club';
DELETE FROM clubs WHERE name = 'Christian Business Society';
DELETE FROM clubs WHERE name = 'Computational & Quantitative Social Science at Cornell';
DELETE FROM clubs WHERE name = 'Cornell Amateur Radio Club';
DELETE FROM clubs WHERE name = 'Cornell Artificial Intelligence Investments club';
DELETE FROM clubs WHERE name = 'Cornell Bitcoin Club';
DELETE FROM clubs WHERE name = 'Cornell Chapter of International City/County Management Association';
DELETE FROM clubs WHERE name = 'Cornell Credit Literacy Student Association';
DELETE FROM clubs WHERE name = 'Cornell Current Club';
DELETE FROM clubs WHERE name = 'Cornell Equity Derivatives Club';
DELETE FROM clubs WHERE name = 'Cornell Growth Capital Club';
DELETE FROM clubs WHERE name = 'Cornell ICPC Club';
DELETE FROM clubs WHERE name = 'Cornell International Finance Club';
DELETE FROM clubs WHERE name = 'Cornell Strategy Solutions Club';
DELETE FROM clubs WHERE name = 'Cornell Technical Analysis Club';
DELETE FROM clubs WHERE name = 'Cornell Venture and Entrepreneurship Club';
DELETE FROM clubs WHERE name = 'Corporate Leadership Club';
DELETE FROM clubs WHERE name = 'Delta Kappa Alpha Professional Cinematic Society';
DELETE FROM clubs WHERE name = 'Diversity on the Street';
DELETE FROM clubs WHERE name = 'Dyson Diversity Council at Cornell';
DELETE FROM clubs WHERE name = 'EMBA Women';
DELETE FROM clubs WHERE name = 'ETA Club at Cornell';
DELETE FROM clubs WHERE name = 'Executive MBA Entrepreneurship Club at Cornell';
DELETE FROM clubs WHERE name = 'Family Business Club';
DELETE FROM clubs WHERE name = 'Federal Reserve Challenge Club';
DELETE FROM clubs WHERE name = 'First Generation Investors at Cornell';
UPDATE clubs SET name = 'GCC' WHERE name = 'Global China Connection at Cornell';
DELETE FROM clubs WHERE name = 'Graduate Student Association for Economics';
DELETE FROM clubs WHERE name = 'Healthcare Artificial Intelligence Collaborative Club';
DELETE FROM clubs WHERE name = 'High Tech Club';
DELETE FROM clubs WHERE name = 'Hospitality Business Club';
DELETE FROM clubs WHERE name = 'Hotel Graduate Student Organization';
DELETE FROM clubs WHERE name = 'Hotel Society, Collegiate Chapter';
DELETE FROM clubs WHERE name = 'Human Capital Association';
UPDATE clubs SET name = 'International Business Consulting' WHERE name = 'International Business Association at Cornell';
DELETE FROM clubs WHERE name = 'Investment Management Club';
DELETE FROM clubs WHERE name = 'Johnson Consulting Club';
DELETE FROM clubs WHERE name = 'Johnson Healthcare Club';
DELETE FROM clubs WHERE name = 'Johnson MPS Student Council';
DELETE FROM clubs WHERE name = 'Johnson Southeast Asian Club';
DELETE FROM clubs WHERE name = 'LAW - Business Law Society';
DELETE FROM clubs WHERE name = 'Media Guild, Inc';
DELETE FROM clubs WHERE name = 'Mu Epsilon Delta';
DELETE FROM clubs WHERE name = 'Nolan Research Student Association';
DELETE FROM clubs WHERE name = 'Old Ezra Finance Club';
DELETE FROM clubs WHERE name = 'Organization of Urban and Regional Studies';
DELETE FROM clubs WHERE name = 'Professional Fraternity Council';
DELETE FROM clubs WHERE name = 'Retail & Luxury Club';
DELETE FROM clubs WHERE name = 'Scholars of Finance - Cornell Chapter';
DELETE FROM clubs WHERE name = 'SensTech';
DELETE FROM clubs WHERE name = 'Social Enterprise Group at Cornell';
DELETE FROM clubs WHERE name = 'The Insurance Club at Cornell';
DELETE FROM clubs WHERE name = 'The MergerSight Group at Cornell';
DELETE FROM clubs WHERE name = 'The TRIBECA Club at Cornell';
UPDATE clubs SET name = 'The Women''s Network' WHERE name = 'The Women';
DELETE FROM clubs WHERE name = 'Undergraduate Human Capital Association';
DELETE FROM clubs WHERE name = 'VC@Johnson';
DELETE FROM clubs WHERE name = 'Ventures Accelerated';
DELETE FROM clubs WHERE name = 'Women';


